In [52]:
#clean data and make simple classifier

import pandas as pd

df1 = pd.read_csv('./data/Kanye_West.csv')
df2 = pd.read_csv('./data/HAIM.csv')


df1.head()

,Unnamed: 0,artist,artist_id,album,album_id,song,song_id,lyrics
0,0,Kanye West,33091467,Donda,46691158,Donda Chant,222687538,"Donda, Donda\nDonda\n\nDonda, Donda, Donda, Do..."
1,1,Kanye West,33091467,Donda,46691158,Jail,222687539,Take what you want\nTake everything\nTake what...
2,2,Kanye West,33091467,Donda,46691158,God Breathed,222687540,I know God breathed on this\nI know God breath...
3,3,Kanye West,33091467,Donda,46691158,Off The Grid,222687541,"Yeah\n\nWhat?\n\nWe off the grid, grid, grid\n..."
4,4,Kanye West,33091467,Donda,46691158,Hurricane,222687542,"See this in 3D, all lights out for me\nAll lig..."

In [53]:
df2.head()

,Unnamed: 0,artist,artist_id,album,album_id,song,song_id,lyrics
0,0,HAIM,14314243,I Know Alone,37212642,I Know Alone,195841352,Been a couple days since I've been out\nCallin...
1,1,HAIM,14314243,I Know Alone,37212642,Don't Wanna,196877715,"Ooh, you, you did me so bad\nWhen I was in the..."
2,2,HAIM,14314243,I Know Alone,37212642,The Steps,194157593,"So baby, when I'm near you\nYou can't feel me,..."
3,3,HAIM,14314243,I Know Alone,37212642,Now I'm In It,194157619,Looking in the mirror again and again\nWishing...
4,4,HAIM,14314243,I Know Alone,37212642,Hallelujah,194157620,"I met two angels, but they were in disguise\nT..."

In [54]:
df1['song'].unique()

array(['Donda Chant', 'Jail', 'God Breathed', 'Off The Grid', 'Hurricane',
       'Praise God', 'Jonah', 'Ok Ok', 'Junya', 'Believe What I Say',
       'Heartless', 'Good Morning', 'Champion', 'Stronger', 'I Wonder',
       'Good Life', "Can't Tell Me Nothing", 'Barry Bonds',
       'Drunk and Hot Girls', 'Flashing Lights', 'Everything I Am',
       'All Of The Lights - Album Version (Edited)', 'Say You Will',
       'Welcome To Heartbreak', 'Amazing', 'Love Lockdown', 'Paranoid',
       'RoboCop', 'Street Lights', 'Bad News', 'See You In My Nightmares',
       'Wake Up Mr. West', "Heard 'Em Say", 'Touch The Sky',
       'Gold Digger', 'Skit #1 (Kanye West/Late Registration)',
       'Drive Slow', 'My Way Home', 'Crack Music', 'Roses',
       'Bring Me Down', 'Ultralight Beam',
       'Father Stretch My Hands Pt. 1', 'Pt. 2', 'Famous', 'Feedback',
       'Low Lights', 'Highlights', 'Freestyle 4', 'I Love Kanye', 'Waves',
       'Dark Fantasy', 'Gorgeous (feat. Kid Cudi & Raekwon)', 'Power',
       'All of the Lights (Interlude)', 'All of the Lights',
       'Monster (feat. Jay-Z, Rick Ross, Nicki Minaj & Bon Iver)',
       'So Appalled (feat. Jay-Z, Pusha T, Prynce Cy Hi, Swizz Beatz & RZA)',
       'Devil In a New Dress (feat. Rick Ross)',
       'Runaway (feat. Pusha T)', 'Hell of a Life', 'Gorgeous', 'POWER',
       'All Of The Lights (Interlude)', 'All Of The Lights', 'Monster',
       'So Appalled', 'Devil In A New Dress', 'Runaway', 'Hell Of A Life'],
      dtype=object)

In [55]:
df1.shape

(82, 8)

In [56]:
df1.isnull().sum()

Unnamed: 0    0
artist        0
artist_id     0
album         0
album_id      0
song          0
song_id       0
lyrics        7
dtype: int64

In [57]:
# Drop rows where song lyrics is nan

df1.dropna(subset=['lyrics'],inplace=True)

In [58]:
df1.shape

(75, 8)

In [59]:
df1_usong = df1.drop_duplicates(subset=['song'])

df1_usong.shape

(68, 8)

In [60]:
df1_usong.head(10)

,Unnamed: 0,artist,artist_id,album,album_id,song,song_id,lyrics
0,0,Kanye West,33091467,Donda,46691158,Donda Chant,222687538,"Donda, Donda\nDonda\n\nDonda, Donda, Donda, Do..."
1,1,Kanye West,33091467,Donda,46691158,Jail,222687539,Take what you want\nTake everything\nTake what...
2,2,Kanye West,33091467,Donda,46691158,God Breathed,222687540,I know God breathed on this\nI know God breath...
3,3,Kanye West,33091467,Donda,46691158,Off The Grid,222687541,"Yeah\n\nWhat?\n\nWe off the grid, grid, grid\n..."
4,4,Kanye West,33091467,Donda,46691158,Hurricane,222687542,"See this in 3D, all lights out for me\nAll lig..."
5,5,Kanye West,33091467,Donda,46691158,Praise God,222687543,"That she wrote, ""Speech to the Young: Speech t..."
6,6,Kanye West,33091467,Donda,46691158,Jonah,222687544,Like who's here when I need a shoulder to lean...
7,7,Kanye West,33091467,Donda,46691158,Ok Ok,222687545,"Okay, now they got me, wanna rap again\nHeal t..."
8,8,Kanye West,33091467,Donda,46691158,Junya,222687546,Junya Watanabe on my wri-wri'\nJunya Watanabe ...
9,9,Kanye West,33091467,Donda,46691158,Believe What I Say,222687547,"(Yo) yo (check our situation), yo\nMy men and ..."

In [62]:
# New lrycis str col
df1_usong['lyric_str'] = [' '.join(text.split('\n')) for text in df1_usong['lyrics']]

df1_usong.head()

C:\Users\Valentin Baltazar\AppData\Local\Temp\ipykernel_23768\1764312726.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1_usong['lyric_str'] = [' '.join(text.split('\n')) for text in df1_usong['lyrics']]

,Unnamed: 0,artist,artist_id,album,album_id,song,song_id,lyrics,lyric_str
0,0,Kanye West,33091467,Donda,46691158,Donda Chant,222687538,"Donda, Donda\nDonda\n\nDonda, Donda, Donda, Do...","Donda, Donda Donda Donda, Donda, Donda, Donda..."
1,1,Kanye West,33091467,Donda,46691158,Jail,222687539,Take what you want\nTake everything\nTake what...,Take what you want Take everything Take what y...
2,2,Kanye West,33091467,Donda,46691158,God Breathed,222687540,I know God breathed on this\nI know God breath...,I know God breathed on this I know God breathe...
3,3,Kanye West,33091467,Donda,46691158,Off The Grid,222687541,"Yeah\n\nWhat?\n\nWe off the grid, grid, grid\n...","Yeah What? We off the grid, grid, grid This ..."
4,4,Kanye West,33091467,Donda,46691158,Hurricane,222687542,"See this in 3D, all lights out for me\nAll lig...","See this in 3D, all lights out for me All ligh..."

In [65]:
df1_usong['lyric_str'][10]

"In the night I hear 'em talk The coldest story ever told Somewhere far along this road He lost his soul to a woman so heartless How could you be so heartless? Oh, how could you be so heartless?  How could you be so, cold as the winter wind when it breeze, yo Just remember that you talkin' to me though You need to watch the way you talkin' to me, yo I mean after all the things that we've been through I mean after all the things we got into Ayo, I know of some things that you ain't told me Ayo, I did some things, but that's the old me  And now you wanna get me back and you gon' show me So you walk around like you don't know me You got a new friend, well, I got homies But in the end it's still so lonely  In the night I hear 'em talk The coldest story ever told Somewhere far along this road ..."

In [10]:
df1_usong.info()

<class 'pandas.core.frame.DataFrame'>
Index: 70 entries, 0 to 71
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  70 non-null     int64
 1   artist      70 non-null     object
 2   artist_id   70 non-null     int64
 3   album       70 non-null     object
 4   album_id    70 non-null     int64
 5   song        70 non-null     object
 6   song_id     70 non-null     int64
 7   lyrics      63 non-null     object
dtypes: int64(4), object(4)
memory usage: 4.9+ KB

In [ ]:
df1_usong['lyrics'].astype()

In [22]:
dtype_counts = df1_usong['lyrics'].apply(type).value_counts()

# Print the counts
print("String:", dtype_counts)
# print("Other data types:", sum(dtype_counts) - dtype_counts.get(str, 0))

String: lyrics
<class 'str'>      63
<class 'float'>     7
Name: count, dtype: int64

In [39]:
for i in df1_usong['lyrics']:
    print(type(i))
    if type(i) == float:
        # print(type(i))
        print(i)

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'float'>
nan
<class 'str'>
<class 'float'>
nan
<class 'str'>
<class 'float'>
nan
<class 'float'>
nan
<class 'str'>
<class 'float'>
nan
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'float'>
nan
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'float'>
nan
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>